### ISSUE TITLE
你好，大佬，如果想使用插件市场，应该放在哪个位置？还有就是有q群吗？

### ISSUE THREAD

**Issue by lucianosummer** [xjw580/Deck-Plugin-Market#1]
![屏幕截图 2024-10-11 091305](https://github.com/user-attachments/assets/d6b97aaa-a9a4-421f-bb6a-bc6d5dfd3632)

**Comment by xjw580** [comment]
主要目前没有其他人做的插件，未来如果有其他人做的插件我会发布到[releases](https://github.com/xjw580/Deck-Plugin-Market/releases), 下载后放入plugin文件夹下

**Comment by lucianosummer** [comment]
嗯，好的。我还想问一下其他群里面看到的反反作弊和环境要不要装
![Screenshot_2024-10-11-09-42-21-875_com tencent mobileqq-edit](https://github.com/user-attachments/assets/54b073ee-0127-4b6a-9755-90465789feaf)

**Comment by xjw580** [comment]
> 嗯，好的。我还想问一下其他群里面看到的反反作弊和环境要不要装 ![Screenshot_2024-10-11-09-42-21-875_com tencent mobileqq-edit](https://private-user-images.githubusercontent.com/96234423/375597488-54b073ee-0127-4b6a-9755-90465789feaf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTE1NTEsIm5iZiI6MTcyODYxMTI1MSwicGF0aCI6Ii85NjIzNDQyMy8zNzU1OTc0ODgtNTRiMDczZWUtMDEyNy00YjZhLTk3NTUtOTA0NjU3ODlmZWFmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAxNDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OWNkODc3ODUxZjBkY2VlZTk3MGY0Y2JhNTkzZTc4ZjUxY2RmN2IzNDdlYjZmZWZhNDAwZWU3OTE5MmNlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hq0qw42ZDw7ZFK_wWuQyiih2-F_X_gWBjb2O50V_xWA)

不知道，不冲突就能装，能不能发我下，我看一下

**Comment by lucianosummer** [comment]
好的，佬，等一下，现在电脑还没开

**Comment by xjw580** [comment]
> 好的，佬，等一下，现在电脑还没开

谢谢，github附件有大小限制，发我邮箱吧，xjw580@qq.com

**Comment by xjw580** [comment]
看了下这个反作弊补丁，主要就是把AntiCheatManager.cs给清空了，炉石外服这个东西好像就是空的，国服新加了这个

**Comment by lucianosummer** [comment]
他们说每次开炉石战网之前都要先运行一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Deck-Plugin-Market] 你好，大佬，如果想使用插件市场，应该放在哪个位置？还有就是有q群吗？ (Issue #1) |

看了下这个反作弊补丁，主要就是把AntiCheatManager.cs给清空了，炉石外服这个东西好像就是空的，国服新加了这个

**Comment by lucianosummer** [comment]
每次更新要运行一遍



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Deck-Plugin-Market] 你好，大佬，如果想使用插件市场，应该放在哪个位置？还有就是有q群吗？ (Issue #1) |

看了下这个反作弊补丁，主要就是把AntiCheatManager.cs给清空了，炉石外服这个东西好像就是空的，国服新加了这个

**Comment by lucianosummer** [comment]
这个应该有用的吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Deck-Plugin-Market] 你好，大佬，如果想使用插件市场，应该放在哪个位置？还有就是有q群吗？ (Issue #1) |

看了下这个反作弊补丁，主要就是把AntiCheatManager.cs给清空了，炉石外服这个东西好像就是空的，国服新加了这个

**Comment by xjw580** [comment]
这个是删除了本地的反作弊，服务器端的反作弊肯定还是有的，就和外服一样

**Comment by xjw580** [comment]
用肯定是有用的

**Comment by lucianosummer** [comment]
哦哦，能帮上佬的忙就行QaQ



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xjw580/Deck-Plugin-Market] 你好，大佬，如果想使用插件市场，应该放在哪个位置？还有就是有q群吗？ (Issue #1) |

用肯定是有用的
